/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_imgsdk_core_NativeImageSdk */

#ifndef _Included_org_imgsdk_core_NativeImageSdk
#define _Included_org_imgsdk_core_NativeImageSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    initSDK
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_imgsdk_core_NativeImageSdk_initSDK
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    initRenderSDK
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_imgsdk_core_NativeImageSdk_initRenderSDK
  (JNIEnv *, jobject, jobject, jobject);


/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    freeSDK
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_imgsdk_core_NativeImageSdk_freeSDK
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    setInputPath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_imgsdk_core_NativeImageSdk_setInputPath
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    setOutputPath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_imgsdk_core_NativeImageSdk_setOutputPath
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    setEffectCmd
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_imgsdk_core_NativeImageSdk_setEffectCmd
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_imgsdk_core_NativeImageSdk
 * Method:    executeCmd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_imgsdk_core_NativeImageSdk_executeCmd
  (JNIEnv *, jobject, jlong, jobject jlistener, jobject jparam);

/*
 * Class:     org_imgsdk_core_BitmapEx
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_imgsdk_core_BitmapEx_allocate
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_imgsdk_core_BitmapEx
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_imgsdk_core_BitmapEx_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_imgsdk_core_BitmapEx
 * Method:    convert2IntArray
 * Signature: (JI)[I
 */
JNIEXPORT jbyteArray JNICALL Java_org_imgsdk_core_BitmapEx_convert2ByteArray
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
